### ISSUE TITLE
Knawat shipping info

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#10]
Knawat has sending shipping tracking number and carrier as order meta

**Acceptance criteria:**
Option 1
1. Select a plugin that handles shipping tracking
2. Mark this plugin optional to our plugin
3. Update developers.knawat.com WooCommerce page support
4. Assign @anouarkacem a task to send data compatible with this plugin

Option 2
1. If the shipping plugin not installed, just show the tracking number for admin and user, on click open carrier website.

**Comment by iamdharmesh** [comment]
@abdullah-albakour please test and mark this closed
