### ISSUE TITLE
 Knawat Dropshipping plug-in

### ISSUE THREAD

**Issue by ssatheesh72** [Knawat/dropshipping-woocommerce#113]
Hi there,

I have installed the Knawat Dropshipping plug-in to my Woocommerce store. Now the trouble is it automatically imports random products until it comes to around 500+. These are randomly chosen  and not the ones I want. Please see attached screenshots.

There is no option on the settings to control or choose what we want to import & sync. Could you please help me out to sort this issue?
[Knawat Dropshipping Screenshots.zip](https://github.com/Knawat/dropshipping-woocommerce/files/3876923/Knawat.Dropshipping.Screenshots.zip)

Thanks & Regards,

Srividhya

**Comment by hamusthekiller** [comment]
@ssatheesh72 
Hello,

How are You Today? I hope You're fine
Sorry for the late response.
Knawat dropshipping plugin has a start-up set up to add your consumer key and secret to begin importing products from your store. Kindly contact support@knawat.com or go to https://support.knawat.com/portal/newticket and submit your store name so We can check your problem or, You can contact me at m.elsayed@knawat.com and I will check the problem and give You a conclusion.

Have a great day.
Regards.
