### ISSUE TITLE
Add support for other translation plugin other than qtranslate-x

### ISSUE THREAD

**Issue by hamusthekiller** [Knawat/dropshipping-woocommerce#130]
We need You to support another translation plugin other than Qtranslate-x because the last update for this plugin was from 2 years ago and It causes a lot of problems in my store. My advice here is You can support Qtranslate-XT plugin as a substitute or, You support a whole new plugin like WPML translation plugin.
Thank You.

**Comment by HazemKhaled** [comment]
It's very soon in #154
