### ISSUE TITLE
New option to delete products when goes out of stock

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#152]
A new option in plugin settings page to enable or disable delete product when it goes out of stock

- [ ] New option in plugin settings to delete product when goes out of stock
- [ ] Default is false for all old customers
- [ ] Should be true by default for all new installations

**Comment by suraj-rathod** [comment]
@HeshamIsmail Please test it

**Comment by suraj-rathod** [comment]
@HeshamIsmail Please test it

**Comment by HeshamIsmail** [comment]
This case is related to #65, we are waiting for the main function to be fixed so we can test this one.

But for the meanwhile:

3. Should be true by default for all new installations

This acceptance criterion is not met, it's no by default.

**Comment by HeshamIsmail** [comment]
This case is related to #65, we are waiting for the main function to be fixed so we can test this one.

**But for the meanwhile:**

***** Should be true by default for all new installations
This acceptance criterion is met.

*****Default is false for all old customers
This acceptance criterion is met.

**Comment by HeshamIsmail** [comment]
As per my tests, the out of stock products were deleted as supposed in the following scenarios:

1-Update by Knawat bulk action.
2-Sync all products.
3-Get from Knawat inside the product.

***** Should be true by default for all new installations
This acceptance criterion is met.

*****Default is false for all old customers
This acceptance criterion is met.

All criteria are met, closing the issue.
