### ISSUE TITLE
Improve product sync strategy.

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/dropshipping-woocommerce#155]
Currently, we are using background process for sync products, and update last sync date at end of whole import finish. this way has few cons like. we have sorting by created date so missing some product to sync, complete whole import is heavy sometime etc...

So, please improve sync using.

1. Use milliseconds
2. Sort by updated
3. Use lastupdate to continue from the same point
4. Save last  sync date and count to show in the progress bar

For now we have hourly cron to initiate sync. we can reduce it to 10-15 mins and need to make related changes in background process.

**Comment by suraj-rathod** [comment]
@HeshamIsmail Please test it

**Comment by HeshamIsmail** [comment]
Sync and import are working normally
