### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#156]
Turkish translation is ready, add it in the next release
https://translate.wordpress.org/projects/wp-plugins/dropshipping-woocommerce/stable/tr/default/?page=1

**Comment by iamdharmesh** [comment]
@HazemKhaled AFAIK we need translations are approved to be included into .po/.mo export file. 
cc: @suraj-rathod

**Comment by suraj-rathod** [comment]
@HeshamIsmail Please test with Turkish translation

**Comment by HeshamIsmail** [comment]
The products are getting imported in Turkish language to Woocomerce normally.
