### ISSUE TITLE
Test plugin with WP 5.6

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/dropshipping-woocommerce#162]
- Make sure plugin working fine with WP 5.6 and latest WooCommerce
- Fix the issue if any

**Comment by suraj-rathod** [comment]
@iamdharmesh Plugin works with the latest beta WordPress development version (5.5.4-alpha-49501)
WooCommerce Version (4.7.1)

@HeshamIsmail Please help to test it

**Comment by suraj-rathod** [comment]
@iamdharmesh Test plugin with 5.6 version all things are working fine with latest WordPress and Woocommerce.

@HeshamIsmail Can you please help to test it

**Comment by suraj-rathod** [comment]
@HeshamIsmail Can you please review both of them and let me know your feedback

**Comment by HeshamIsmail** [comment]
#166  and #167  are resolved 

We have opened enhancement tickets for the behavior without the Featured Image by URL plug-in 

https://github.com/Knawat/dropshipping-woocommerce/issues/170
https://github.com/Knawat/dropshipping-woocommerce/issues/171
