### ISSUE TITLE
Release new version v2.2.0

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/dropshipping-woocommerce#163]
- Update Translation file
- Add change log
- Update Readme file for new version
- Update version in plugin file
- Create tag to release it on wp.org

**Comment by HazemKhaled** [comment]
This action should update versions everywhere https://github.com/Knawat/dropshipping-woocommerce/blob/master/.github/workflows/main.yml

**Comment by suraj-rathod** [comment]
@iamdharmesh I have just noticed WooCommerce has a new version after we did a test with this, would you like to test our plugin with this version also please let me know

**Comment by iamdharmesh** [comment]
Yes @suraj-rathod please test it with new WC version and also update in readme.txt wp compatible version after testing done.

cc: @HazemKhaled

**Comment by suraj-rathod** [comment]
@iamdharmesh i have tested with the new WC version and i have updated the files

**Comment by iamdharmesh** [comment]
Closing as v2.2.0 released.
