### ISSUE TITLE
Import as product category or tags added option from settings tab

### ISSUE THREAD

**Issue by suraj-rathod** [Knawat/dropshipping-woocommerce#164]
Category and tag import changes with option 
Product parent category import issue

**Comment by iamdharmesh** [comment]
@HeshamIsmail please help with test this.

**Comment by HeshamIsmail** [comment]
Hello @suraj-rathod ,

In order to debug your issue, I want to know more info. Also, there could be some conflicts with other WordPress plugins. Could you disable all the plugins leaving only the Knawat plugin, and check if everything is working? If not provide me with detailed steps to reproduce the issue.

**Comment by suraj-rathod** [comment]
@HeshamIsmail Yes please let me know what info you need and from where are you checking it so i can help to disable the plugin

**Comment by HeshamIsmail** [comment]
Hello @suraj-rathod,

Hazem has provided two templates for bugs and features, please kindly use them to submit the issue in detail.

https://github.com/Knawat/dropshipping-woocommerce/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

https://github.com/Knawat/dropshipping-woocommerce/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

Thank you,

**Comment by suraj-rathod** [comment]
Thank you @HeshamIsmail let me check those templates

**Comment by suraj-rathod** [comment]
Acceptance Criteria:

Added new options for products on settings tab import as category or tag 

- [ No ] None of the imported knawat product's will import as category or tag 
- [ Yes (Product Category) ]  knawat imported product's category will import as WooCommerce product category 
- [ Yes (Product tag) ] knawat imported product's category will import as WooCommerce product tag



![image](https://user-images.githubusercontent.com/36834155/101158594-fa07d400-3651-11eb-87b3-0aa96cae5ebe.png)

**Comment by suraj-rathod** [comment]
@HeshamIsmail please help to test this.

**Comment by HeshamIsmail** [comment]
@suraj-rathod 
**Test Subject:** 

new options for products on settings tab import as category or tag

[ No ] None of the imported knawat product's will import as category or tag
[ Yes (Product Category) ] knawat imported product's category will import as WooCommerce product category
[ Yes (Product tag) ] knawat imported product's category will import as WooCommerce product tag

**Testing steps:** 

1-Went to Knawat dropshipping settings and chose from Categorized Products: "No"
2-Ran import

Result: None of the imported Knawat product's was imported as category or tag

3-Went to Knawat dropshipping settings and chose from Categorized Products: "Yes (Product Category)"
4-Ran import

Result: Knawat imported product's category imported as WooCommerce product category

5-Went to Knawat dropshipping settings and chose from Categorized Products: "Yes (Product tag)"
6-Ran import

Result: Knawat  imported product's category will import as WooCommerce product tag

**Test result: Pass**
