### ISSUE TITLE
Import latency Wordpress version 5.6

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#166]
**Describe the bug**
Import product is taking longer than normal and it the behavior became more and more clear with Word press 5.6
I imported 41 products in 1 hour 40 minutes from Knawat on the local store.

**To Reproduce**
1. Go to Knawat plug
2. Click on 'Import'

**Expected behavior**
The products gets imported in a way long time more than usual 

**Screenshots**
![image](https://user-images.githubusercontent.com/74185849/102010778-5608e180-3d51-11eb-8041-79c69b2e24b8.png)
![image](https://user-images.githubusercontent.com/74185849/102010800-64ef9400-3d51-11eb-8a90-5c463039c892.png)

**Enviroment (please complete the following information):**
 - OS: Windows
 - Browser Microoft edge
 - Plugin Version 2.1.1
 - WordPress Version 5.6

**Comment by suraj-rathod** [comment]
I have imported 60 products and it was taking approx 45 minutes into a local store @iamdharmesh @HeshamIsmail but import has an issue while importing multiple products in my case i have imported 60 but only 42 products imported and 2 product are failed

**Comment by iamdharmesh** [comment]
Hello @HeshamIsmail @suraj-rathod ,

If you are testing in local and featured image by URL is not installed then it will depends on internet speed of your connection. but if this is not the case then we need to debug more deep with import. @suraj-rathod please help to check on this further.

**Comment by suraj-rathod** [comment]
@iamdharmesh I will check it and let you know

**Comment by suraj-rathod** [comment]
@iamdharmesh I have installed the featured image by URL plugin and again import 60 products so in approx 20 minutes of time 59    products are imported and not any failed product with this import and total 350 plus products are updated so it has approx 28 minutes 

after that, I have again started the product import with another 60 product

**Comment by HeshamIsmail** [comment]
Yesterday I imported 2 products in 10 minutes without installing and activating local and featured image by URL.
My internet connection was good enough for the process.

![image](https://user-images.githubusercontent.com/74185849/102451864-61f2ed00-404a-11eb-8896-9dd817ac58ca.png)

https://www.loom.com/share/0a288d4358864204b74b2a43712f1a1a?sharedAppSource=personal_library

https://www.loom.com/share/c3e45082163e4dba9de2fbacbd5cb8f6?sharedAppSource=personal_library

Today after I installed **local and featured image by URL**, I was able to import 27 products in less than 2 minutes.

https://www.loom.com/share/df1865cbe5f446a986b567dc9037587c

I uninstalled the  **local and featured image by URL** plug-in, deleted all products and reimported products, I was able to import 10 products in more than 10 minutes.

https://www.loom.com/share/f5e22537650246f7bde850da181be364?sharedAppSource=personal_library

https://www.loom.com/share/dd2e3d8de016448290b8c9cf78dc0be8?sharedAppSource=personal_library

@suraj-rathod

**Comment by suraj-rathod** [comment]
@HeshamIsmail Can you please re-test it recently i have tested with up to 60 products with featured image by URL plugin it's imported in approx 20 minutes

**Comment by HeshamIsmail** [comment]
Products are imported fast when the Featured Image by URL is activated.

We'll close this issue and open an improvement issue for the behavior without the featured image by URL for future release.
