### ISSUE TITLE
Import counter is not counting the imported products V5.6

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#167]
**Describe the bug**
When you import products from Knawat plug-ins, the counter doesn't count the imported products

**To Reproduce**

1. Go to Knawat plugin
2. Click on import

Expected result: Products start to be imported and the counter displays the imported, updated, and failed imported products.
Result: Products start to be imported but the counter stays Zero the whole process

**Expected behavior**
Products start to be imported and the counter displays the imported, updated, and failed imported products.

**Screenshots**
![image](https://user-images.githubusercontent.com/74185849/102077269-10641b80-3e1a-11eb-9d60-db6eae276b1c.png)
![image](https://user-images.githubusercontent.com/74185849/102077329-27a30900-3e1a-11eb-8973-28dc538f5127.png)

**Enviroment (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Plugin Version 2.1.1
 - WordPress Version 5.6
 - WooCommerce Version [e.g. 5.2]

**Comment by suraj-rathod** [comment]
Fix the issue with the latest PR #168

**Comment by suraj-rathod** [comment]
This issue is fixed with the latest merge request so @HeshamIsmail can you please check it again and let us know your feedback

**Comment by HeshamIsmail** [comment]
@suraj-rathod 

I checked this morning and for more than 10 minutes no products were counted.
However, two products were imported.

I captured 2 videos of the behavior and a screenshot.

https://www.loom.com/share/0a288d4358864204b74b2a43712f1a1a?sharedAppSource=personal_library

https://www.loom.com/share/c3e45082163e4dba9de2fbacbd5cb8f6?sharedAppSource=personal_library

![image](https://user-images.githubusercontent.com/74185849/102351468-8ea9f480-3fb7-11eb-9f52-7c1e5c012fe2.png)

**Comment by suraj-rathod** [comment]
@HeshamIsmail You need to reload the to review the process

**Comment by suraj-rathod** [comment]
@HeshamIsmail For reviewing the counter on a page needs be refresh every time so you can visible the numbers so, please try to check like that and let me know

**Comment by HeshamIsmail** [comment]
My latest test with Suraj showed that by refreshing the page 3 times every time we need to get the count.

As per Dharmesh:

It's a background process which update counts in db and this page show counts from db
So, there are some cases where count not updated but product already imported in website.
--------------------------------------------------------
We'll keep this issue open till we resolve 166 as we agreed

**Comment by HeshamIsmail** [comment]
The counter is working perfectly when the Featured Image by URL is activated.

We'll close this issue and open an improvement issue for the behavior without the featured image by URL for future release.
