### ISSUE TITLE
Don't update variations with zero price

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#178]
### Updated Description
Some variations prices updated to zero while it's getting archived, so no need to update the prices in case it's Zero, while update the stock only

**Issue:**

Few products are imported to Woocommerce with two prices which is not the same behavior on Zapp.

**Steps to replicate:** 

1-Import the products below to Woocommerce store:
                                                                                                 -MGGDPRGZHWY710-3415
                                                                                                 -MGGDPRMGTRLK10-3568
                                                                                                 -MGGDPRMGGZHW712-3597

2-Go to your woo-commerce store admin
3-Go Catalog->All products
4-Check the imported products

Expected result: All products have the prices set on Zapp after calculating the profit.
Result: Those three products have two prices one of them is not mentioned on Zapp. 

**Troubleshooting steps:**

1-Tested the behavior on different platforms only occurred on Woocommerce
2-Reimporting products don't fix the prices.

**Attachments:**

1-Screenshot for the behavior.

![image](https://user-images.githubusercontent.com/74185849/103641212-7435bc00-4f62-11eb-9578-8084a8934d90.png)

**Enviroment (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Plugin Version 2.2
 - WordPress Version 5.6
 - WooCommerce Version 4.8

**Comment by HeshamIsmail** [comment]
@suraj-rathod 
@iamdharmesh 


Please check it

**Comment by suraj-rathod** [comment]
i will check it and update you soon @HeshamIsmail

**Comment by suraj-rathod** [comment]
@HeshamIsmail There will be different prices for a single product in variations so for that reason it will be displayed like this

https://www.screencast.com/t/n4fX0hiDk
https://www.screencast.com/t/1o5ebGvYQFXB

**Comment by iamdharmesh** [comment]
Hello @HeshamIsmail It looks like issue in data can you please check with Nirali for the same.

**Comment by HeshamIsmail** [comment]
Asked Nirali to check the products

**Comment by neer14** [comment]
@HeshamIsmail  @HazemKhaled 
this issue occurs because it is displaying price of archived variants too.
1. we are storing old variants (which are not in update product variants) as archived variants, we need to store this old variant with old price
2. sometimes xml don't send price in few variants of product so we store variant as archived variant with price 0, while other variants are stored with price
eg.
- variant: S-RED, price : not sent
will be stored as => variant: S-RED, price : 0, archive: true
- variant: S-GREEN, price : 69.6
will be stored as => variant: S-RED, price : 69.6, archive: false

if we can ignore archived variants while showing price, then this issue can be solved.

**Comment by HazemKhaled** [comment]
Thanks for Clearification @neer14 , issue updated

**Comment by suraj-rathod** [comment]
@HeshamIsmail Please test it

**Comment by HeshamIsmail** [comment]
One of the previously reported products is still showing duplicate prices:

**MGGDPRMGTRLK10-3568**

![image](https://user-images.githubusercontent.com/74185849/112473826-e8bd1180-8d7f-11eb-803c-e6bd8aa8ec84.png)

**Comment by suraj-rathod** [comment]
It's not duplicate price @HeshamIsmail here we get the multiple prices from the API as per the variant so we are displaying that also it's not compulsory to have the same price for all variants here you can see in below screen i am getting a different price for variations so we can not consider as a bug here.

https://www.screencast.com/t/5D4LvFWazy
https://www.screencast.com/t/Kf4eUC5Bm

@iamdharmesh Please verify it and update to @HazemKhaled

**Comment by iamdharmesh** [comment]
@HeshamIsmail based on screenshot its issue from data side. we need to fix it at product sourcing level.
cc: @HazemKhaled

**Comment by HazemKhaled** [comment]
It's WooCommerce feature to have multiple prices @HeshamIsmail

**Comment by HeshamIsmail** [comment]
The products showing the odd behavior doesn't supposed to have different prices for each variant. We are not asking to cancel the feature for products that requires different prices for different variants.
If @Niralifix is successfully applied and you both confirm it @Dharmesh Patel @Hazem
We may report those products to the Knawat product team if this is the case.

**Comment by HeshamIsmail** [comment]
This issue has passed, the duplicate price displaying is due to adding variation to Zero quantity which I opened a separate ticket for it [#195 ](https://github.com/Knawat/dropshipping-woocommerce/issues/195)

Closing this one.
