### ISSUE TITLE
Specific products are imported with two prices and duplicate variations

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#183]
**Issue**:

Few specific products are imported to Woocommerce with duplicate variations and two different prices 

**Steps to replicate:**

1-Import the products to Woocommerce:
                                              MOAT44800
                                            MOAT44738
                                            MOAT44793

2-Open the Woocommerce store admin.
3-Go Catalog->All products.

Result: The products will have two prices
Expected result: Each product should have only one price.

4- Open each product
5-Check variations sections

Result: Variations are duplicated, the second batch is mirrored 
Expected result: Variations shouldn't be duplicated

**Troubleshoot**:

1-Tested the same products on all other platforms.
2-Checked the products on API                    

**Attachments:**

1-Screenshot showing the behavior on the Woocommerce store:

![image](https://user-images.githubusercontent.com/74185849/107037993-f79a3580-67cc-11eb-96f2-69e454604ec8.png)

![image](https://user-images.githubusercontent.com/74185849/107038035-01bc3400-67cd-11eb-9a8d-c4053927c64c.png)

**Enviroment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Plugin Version: 2.2.0
 - WordPress Version: 5.6.1
 - WooCommerce Version:4.9.2

**Comment by suraj-rathod** [comment]
@HeshamIsmail We are getting the mirror record from the API there will be an issue with data we are getting size information into the color so for this reason, it will display like it.

https://www.screencast.com/t/SxLbvVfgiPn
https://www.screencast.com/t/2tg1vevyS
https://www.screencast.com/t/5MsyyT97tyyQ
https://www.screencast.com/t/9KvEQ09DcT

**Comment by iamdharmesh** [comment]
Hello @HeshamIsmail It looks like issue in data can you please check with Nirali for the same.

**Comment by HeshamIsmail** [comment]
Asked Nirali to check the products

**Comment by neer14** [comment]
@HeshamIsmail  
i see the product is updated on 2021-02-24. and there are no duplicate variants showing in products.
can you check the product again?

**Comment by HeshamIsmail** [comment]
Hello @neer14 , retested the behavior, the issue is still remaining.

![image](https://user-images.githubusercontent.com/74185849/109275058-46177e80-7825-11eb-9550-b2716d155410.png)

**Comment by neer14** [comment]
@HeshamIsmail 
I am asking you to chack if duplicate variants issue(from screenshot in issue description) is solved or not?

I explained price issue here: https://github.com/Knawat/dropshipping-woocommerce/issues/178

**Comment by HeshamIsmail** [comment]
@neer14 The double variations behavior is still occurring on the same products.

![image](https://user-images.githubusercontent.com/74185849/109489425-e83e9d00-7a97-11eb-8c12-3bc09a92f126.png)

**Comment by HeshamIsmail** [comment]
As per our last meeting: 

Supplier didn't hide the archived variations, we don't have anything that can be done from our end as it's not affecting behavior.

The XML file has been fixed.

Closing this issue.
