### ISSUE TITLE
[dropshipping-woocommerce-master] Import counter is counting more than the real imported product count

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#191]
**Describe the bug**

The import counter is counting way more than the real imported product count

**To Reproduce**
1. Create a new Woocommerce store on Knawat
2. Import 20 products
3. Link the store  to Woo commerce from Knawat dropshipping Woocommerce plugin
4. Start import from Knawat dropshipping Woocommerce plugin
5. Check counter.

**Expected behavior**
The counter should display the same count of the imported products.

**Screenshots**

![image](https://user-images.githubusercontent.com/74185849/113002364-5e5b2000-917a-11eb-9c4d-e30b980ce9e6.png)

![image](https://user-images.githubusercontent.com/74185849/113002426-6fa42c80-917a-11eb-9668-f435f9d319f1.png)

**Enviroment (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome
 - Plugin Version The latest "dropshipping-woocommerce-master"
 - WordPress Version: 5.7
 - WooCommerce Version [e.g. 5.2]

**Additional context**

**Comment by iamdharmesh** [comment]
@suraj-rathod this is due to recent sync improvement. you have to update import completion rule as we discussed over call. other wise import will keep updating same products again and again.

**Comment by suraj-rathod** [comment]
@HeshamIsmail Please test it and share your feedback

**Comment by HeshamIsmail** [comment]
The counter is now working normally as supposed.
