### ISSUE TITLE
[dropshipping-woocommerce-master] The plug-in is not importing more than 30 products

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#192]
**Describe the bug**

Knawat plugin isn't importing more than 30 products 

**To Reproduce**
1. Go to Zapp
2. Import 100 products.
3. Get back to the linked Woocommerce store
4. Start importing from Knawat dropshipping plug-in.

**Result**
The products import stops at 30 product maximum

**Expected behavior**
All products get imported

**Screenshots**

![image](https://user-images.githubusercontent.com/74185849/113716523-5f003300-96f3-11eb-9b51-78fd8191ae09.png)

**Enviroment (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Plugin Version: dropshipping-woocommerce-master
 - WordPress Version: 5.7
 - WooCommerce Version: 5.1.0

**Additional context**

**Comment by iamdharmesh** [comment]
@suraj-rathod please help to check on this.

**Comment by suraj-rathod** [comment]
@HeshamIsmail I have import 60 products and import products into the store and i got all the records and more than 30 plus records you review it from the below video and screenshorts.

Can you please review it again and let me know.

https://www.screencast.com/t/7hEOLR7hSJw3
https://www.screencast.com/t/O0hHjNst4SEX
https://www.screencast.com/t/UT8wAKgZ0

**Comment by HeshamIsmail** [comment]
The issue is still occurring showing the error on the right and imported is getting failed after 24 products:

![image](https://user-images.githubusercontent.com/74185849/114374056-e7675380-9b8b-11eb-8bcd-5aac6c686bb2.png)

**Comment by suraj-rathod** [comment]
@HeshamIsmail let me test it again it i will update you soon

**Comment by iamdharmesh** [comment]
@suraj-rathod and @HeshamIsmail I think better to check this over call. So, you both have better idea on the issue.

**Comment by HeshamIsmail** [comment]
After setting a timeout limit on my environment, import is working perfectly on all scenarios:

![image](https://user-images.githubusercontent.com/74185849/114991796-abd9cb80-9ea2-11eb-8d35-abbdb6cc1ba6.png)

1.Imported products successfully without categories or tags.
2.Imported products successfully products by tags.
3.Imported products successfully by categories.
