### ISSUE TITLE
CRITICAL Uncaught Error while importing products with categories

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/dropshipping-woocommerce#204]
**Describe the bug**

While user importing products with categories, the import stops, and an error fatal displays in logs as below:

**"2021-06-21T00:05:51+00:00 CRITICAL Uncaught Error: Cannot use object of type WP_Error as array in /var/www/vhosts/****.com/httpdocs/wp-content/plugins/dropshipping-woocommerce/includes/class-dropshipping-woocommerce-importer.php:800"**

**To Reproduce**
1. Import products with categories

**Result**:

After a while, the import stops and a fatal error occurs in the logs.

**Expected behavior**

Products should be imported with products normally without errors

**Troubleshooting steps:**
1-The issue was fixed locally by setting a time limit, but it didn't fix the issue on customer servers. 

**Enviroment (please complete the following information):**
 - OS: Cpanel
 - Browser Chrome
 - Plugin Version 2.2.0
 - WordPress Version 5.7.1
 - WooCommerce Version 5.4.1

**Comment by suraj-rathod** [comment]
@HeshamIsmail I have checked for error which you have given over mail but for the two stores it's working fine as below

1) jojksa :  update and import successfully working
   https://www.screencast.com/t/iLfC2PTWuy5
   https://www.screencast.com/t/MoESE3xm
   
2) shatay : update successfully working   
   https://www.screencast.com/t/zyzSdazs
   
   For other stores, it's not working or stopped after half the import process issue is related to Arabic string of category i am working on it update you shortly over here.

**Comment by suraj-rathod** [comment]
3. sindbad :  update and import successfully working
   https://www.screencast.com/t/OkD8kNguQY
   
4. shop-66.com : update and import successfully working
   https://www.screencast.com/t/dkrarRBCEy

@HeshamIsmail Please review it and let me know

**Comment by suraj-rathod** [comment]
@HeshamIsmail i have an update few changes on sindbad and shop-66 and import functionality is working so can you please it from your end and let me know.

The issue is in Arabic string with few some character is not supported for that reason import is broken not it's fixed.

**Comment by HeshamIsmail** [comment]
@suraj-rathod The issue is now fixed.
Closing this ticket

Thank you very much for your assistance.
