### ISSUE TITLE
Update JSON Order structure as per new knawat-mp API stucture.

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/dropshipping-woocommerce#29]

**Comment by HazemKhaled** [comment]
@iamdharmesh more info here pls

**Comment by iamdharmesh** [comment]
@HazemKhaled I have added few more fields to `POST` orders body for later use. like `('id', 'parent_id', 'number', 'order_key', 'created_via', 'currency', 'discount_total', 'discount_tax', 'shipping_total', 'shipping_tax', 'cart_tax','total','total_tax','prices_include_tax', 'customer_note', 'transaction_id', 'status', 'line_items', 'billing', 'shipping', 'pdf_invoice_url', 'pdf_invoice_url_rtl' )`
