### ISSUE TITLE
Fetch and sync Knawat order status and regarding information into orders.

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/dropshipping-woocommerce#31]

**Comment by abdullah-albakour** [comment]
- [ ] Check for orders and sub-orders
- [ ] Update order status as Knawat end
- [ ] Add shipping info after the order status is completed

**Comment by abdullah-albakour** [comment]
Create order and update is failed as below:

Steps:
Enable BACS (bank transfer) payment gateway 
Change Knawat settings to from Dropshipping > Settings > Order Status for send order to knawat > to Processing
Place an order with BACS payment gateway
Change order status to processing from store's backend 

Actual result:
The order sent as an update to Knawat MP and the API returns order is not found

Expected result:
The plugin should send all the order details once the order is in the status selected from settings

**Comment by iamdharmesh** [comment]
Interval Selection in Settings Section

![image](https://user-images.githubusercontent.com/10613171/43819764-c480c8d4-9b01-11e8-8154-fbbaabcae6dc.png)

**Comment by iamdharmesh** [comment]
@abdullah-albakour ORDER UPDATE part is pending as API is still not working at GET `orders/` endpoint

**Comment by HazemKhaled** [comment]
New API fixed and deployed, @abdullah-albakour pls test here again

**Comment by iamdharmesh** [comment]
@HazemKhaled shipping details and knawat status is still not returned by API. I will work on it MP & Klayer side and will update code here.

**Comment by iamdharmesh** [comment]
@abdullah-albakour done. this is ready for test now

**Comment by abdullah-albakour** [comment]
@iamdharmesh 
Order status isn't being syncronized from Knawat on Dev Environment.
