### ISSUE TITLE
Knawat product prices are not imported with products

### ISSUE THREAD

**Issue by abdullah-albakour** [Knawat/dropshipping-woocommerce#39]
Steps:
Go to testaro.abdullah.sindrela.com
Navigate to knawat dropshipping 
Click on Start import

Expected result:
Products should be imported with prices

Actual result:
Products should have regular prices 

screenshot attached

![image](https://user-images.githubusercontent.com/29152917/43469210-4ed85570-94ee-11e8-9506-d7bcc1230cce.png)

**Comment by iamdharmesh** [comment]
@abdullah-albakour it was MP API issue. fixed now please test this now.
