### ISSUE TITLE
Readonly cost field

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#4]
In edit page, show read-only cost field when click on a variation

**Comment by iamdharmesh** [comment]
@abdullah-albakour can you please test and close this. Also, please test with latest code of branch v1.2.0

![knawat_cost](https://user-images.githubusercontent.com/10613171/37276675-55a15ab0-25da-11e8-9be5-8d34a241bb48.png)

**Comment by abdullah-albakour** [comment]
Done, working fine 

Please add Knawat currency ($) to the field name, to be 'Knawat Cost ($)' and make it same font-weight as WooCommerce fields titles

Screenshot:
 ![download 1](https://user-images.githubusercontent.com/29152917/37822669-285b365e-2e98-11e8-82cd-9198d7c3b073.png)

**Comment by abdullah-albakour** [comment]
@iamdharmesh 
Knawat sends the cost in USD whatever the seller's website currency is, so we need to change the dynamic currency symbol beside cost to static **$** 

![image](https://user-images.githubusercontent.com/29152917/45357480-09ad2500-b5cf-11e8-8e95-e6d7afd4d6a3.png)
