### ISSUE TITLE
When user delete product from store delete it from MP

### ISSUE THREAD

**Issue by abdullah-albakour** [Knawat/dropshipping-woocommerce#44]
If the user deletes a product permanently from the store, delete it from MP
If he moves a Knawat product to trash, then show notice, The product will be imported again from Knawat, if you don't want this product, then delete it permanently after you click on trash.

**Comment by iamdharmesh** [comment]
@HazemKhaled Product DELETE MP API needed for this.

**Comment by iamdharmesh** [comment]
@abdullah-albakour  please test it

**Comment by samer2023** [comment]
Hello , the customer with email id: ahlkvist@hotmail.com is facing an issue when removing item 100251281, I2136AZ18SPBR155 deleted them several times from his store. And from the trash , but they keep getting back when synced. store name: 
http://Hoodrats.se

**Comment by samer2023** [comment]
Hello, We need to add a warning message for Woocommerce users that assigning a  big product batch size in Dropshipping settings might lead to server overload /problem and the acceptable product batch size should not exceed 100 / Interval
