### ISSUE TITLE
Send Shipping same as Billing Address if the customer placed order only with billing address

### ISSUE THREAD

**Issue by abdullah-albakour** [Knawat/dropshipping-woocommerce#47]
Steps:
Go to testaro.abdullah.sindrela.com
Navigate to Knawat product
Select and Add to cart
Fulfill order details as billing only

Expected result:
The plugin should send full data (copy of billing address) in shipping address fields if it's empty.

Actual result:
The plugin sends the order as is with null fields in the shipping address.

**Comment by abdullah-albakour** [comment]
![image](https://user-images.githubusercontent.com/29152917/43642791-98a91762-9731-11e8-9cc9-075cadd6a7c2.png)

**Comment by iamdharmesh** [comment]
@abdullah-albakour not able to reproduce this issue at local and also woo-commerce is also take a billing address as a shipping address if its not there. however, I have added support for handle this in plugin.
