### ISSUE TITLE
Support making products under specific seller in Dokan stores

### ISSUE THREAD

**Issue by abdullah-albakour** [Knawat/dropshipping-woocommerce#60]
In my Dokan store, I need all of Knawat products to be added under specific seller by select the products author from Knawat plugin settings.

Acceptance criteria:
1. If Dukan plugin installed show new option in Knawat store settings to select default user (seller)

**Comment by iamdharmesh** [comment]
@abdullah-albakour added support for Dokan
![image](https://user-images.githubusercontent.com/10613171/45160986-69d74c00-b208-11e8-8798-307e05443168.png)
