### ISSUE TITLE
problem withe extra images for products

### ISSUE THREAD

**Issue by emadraz** [Knawat/dropshipping-woocommerce#62]
hi
i am from 
duccany.com

can You resolve appearing of Extra images 
if you can do it as it was before 
our mobile app can not loop extra images for the product
we need to send images from plugin 
https:/duccany.com/wp-json/wooconnector/product/getproduct

all the images and extra images must be 
wooconnector_crop_images

for your information before the last change from your side every thin is working good 
please check as soon as possible

thank you

**Comment by abdullah-albakour** [comment]
@iamdharmesh 
Could you please help him and respond here

**Comment by iamdharmesh** [comment]
Hello @emadraz,

Thanks for reaching out to us and sorry for the inconvenience happen to you.

I have take a look on your issue and found that plugin you are using for app is generates resized images when product create or update from wp-admin edit product screen only. that mean if you create product or update product from edit product screen then it will generate resized images and `wooconnector_crop_images` will work fine. Our plugin is import products directly. So, plugin you are using for app is not generating resized images.

So, if you update any product from wp-admin then you can see images are there for that product in plugin's API.  for fix this issue you have to trigger a resize images call on `woocommerce_new_product` and `woocommerce_update_product` actions. you can contact your app plugin's author for more information. Also, we can guide you for fix this.

Thanks,
Dharmesh

**Comment by emadraz** [comment]
which plugin should i edit

Woocommerce or wooconnector

And woocommerce_update_product where it's located in any file ?

**Comment by iamdharmesh** [comment]
Hello @emadraz,

You have to edit wooconnector plugin for fix this issue. but edit plugin is not a best practice because changes will get overwrite during plugin update. You can fix issue with below code by putting it in theme's function file. (**Note:** code is not tested with your website so please give it try its working for you not)
After putting this code into your theme's function file you have to run product import by press "Start Import" button. after finish import you can see results for this.

```
if( class_exists( 'WooconnectorProducts' ) ){
	$wooconnector_products = new WooconnectorProducts();
	add_action( 'woocommerce_update_product', 'knawat_fix_for_wooconnector' );
	add_action( 'woocommerce_new_product', 'knawat_fix_for_wooconnector' );
	add_action( 'knawat_wooconnector_image_resizer', array( $wooconnector_products, 'update_thumnail_woo') );
	function knawat_fix_for_wooconnector( $post_id ){
		if( empty( $post_id ) ){
			return;
		}
		$post = get_post( $post_id );
		do_action( 'knawat_wooconnector_image_resizer', $post_id, $post );
	}
}
```

Let us know if its not work for you.

Thanks,
Dharmesh

**Comment by emadraz** [comment]
Hi please if you can help me
Wich file should I add this code ?

Thank you

**Comment by iamdharmesh** [comment]
Hello @emadraz,

You should add this code to your theme's functions.php file.

Thanks,
Dharmesh

**Comment by iamdharmesh** [comment]
Hello @emadraz,

Is this issue fixed? let us know if you still experience it.

Thanks,
Dharmesh

**Comment by deounix** [comment]
Hi @iamdharmesh

Sorry for disturb u but I'm not php developer, so I'm trying to understand what causes this problem.

What I did (before):
I edited functions.php in our wordpress theme after that I re-update (re-import) products. and every thing work good (I can get the photo url from the api)

Now I can't, Api not sending photo urls

**Comment by iMuzician** [comment]
> Hello @emadraz,
> 
> You have to edit wooconnector plugin for fix this issue. but edit plugin is not a best practice because changes will get overwrite during plugin update. You can fix issue with below code by putting it in theme's function file. (**Note:** code is not tested with your website so please give it try its working for you not)
> After putting this code into your theme's function file you have to run product import by press "Start Import" button. after finish import you can see results for this.
> 
> ```
> if( class_exists( 'WooconnectorProducts' ) ){
> 	$wooconnector_products = new WooconnectorProducts();
> 	add_action( 'woocommerce_update_product', 'knawat_fix_for_wooconnector' );
> 	add_action( 'woocommerce_new_product', 'knawat_fix_for_wooconnector' );
> 	add_action( 'knawat_wooconnector_image_resizer', array( $wooconnector_products, 'update_thumnail_woo'), 10, 2 );
> 	function knawat_fix_for_wooconnector( $post_id ){
> 		if( empty( $post_id ) ){
> 			return;
> 		}
> 		$post = get_post( $post_id );
> 		do_action( 'knawat_wooconnector_image_resizer', $post_id, $post );
> 	}
> }
> ```
> Let us know if its not work for you.
> 
> Thanks,
> Dharmesh



Mr. @iamdharmesh  ,  our developer did what you mentioned on your last post. its work ok . then knawat team has update their plugin to fix an issue after that we got the problem again. 
and we checked the functions.php , the code you had mentioned on your last post still there with no change. today is thursday we have 2 days left this week.
we had stopped our work more than 5 days ( emails only _send replay forward_ ) waiting to solve this issue. 
thats why i came here, we need your support please. 

Cc: 
@deounix  
@emadraz

**Comment by iamdharmesh** [comment]
Hello @XMusician,

Sorry for the inconvenience happen to you. 

We have noted that "Featured Image by URL" plugin active on website. This plugin is for use CDN images instead of local images. Thats creates conflict with your API. so we have to remove it for keep working your API flawlessly. Our support team will apply below steps to fix issue and it will get resolved.

1.) Delete products
2.) Remove "Featured image by URL"
3.) Import products

Feel free to contact us if you have any other difficulties.

Thanks,
Knawat Team

Cc:
@deounix
@emadraz

**Comment by XMusician** [comment]
Thank your for assistance, its work fine now.
And sorry for late replay.
