### ISSUE TITLE
TEST: Migrate old apps

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#66]
We need criteria for existing users once they upgrade the plugin, what will happen?

Check List:

- [ ] All old products keep updating with the new way
- [ ] All old webhook should be deleted automatically
- [ ] Automatic change store type from WooCommerce to WooCommerce 2
- [ ] All API keys that start with Knawat - API should be deleted automatically
- [ ] Show big and important notice that user should get his API key and secret from knawat dashboard

What else do you think?

**Comment by iamdharmesh** [comment]
@HazemKhaled we need API endpoint for this in MP "Automatic change store type from WooCommerce to WooCommerce 2" please suggest.

**Comment by iamdharmesh** [comment]
@abdullah-albakour except "Automatic change store type from WooCommerce to WooCommerce 2" all other are testable.

**Comment by HazemKhaled** [comment]
Now customer can't get API Key unless they click upgrade, this button migrate from old WooCommerce plugin to the new one
