### ISSUE TITLE
Fix Language Tag([:ar], [:en]) in Product Attributes in Backend.

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/dropshipping-woocommerce#77]
Here is few images for the issue.

**Custom Attributes**
![image](https://user-images.githubusercontent.com/10613171/47696779-4a6c0680-dc2e-11e8-80c2-adeaaa29d1fe.png)

**Global Product Attributes**
![image](https://user-images.githubusercontent.com/10613171/47696806-6ff91000-dc2e-11e8-8b32-11ae50d33b92.png)

**Attribute Selection in Variations Section**
![image](https://user-images.githubusercontent.com/10613171/47696811-77201e00-dc2e-11e8-8d0e-cb1a2c4ac4b1.png)

**Comment by HazemKhaled** [comment]
I think this is woocommerce-qtranslate-x#41 issue, not ours
