### ISSUE TITLE
Connect your store with knawat Popup

### ISSUE THREAD

**Issue by abdullah-albakour** [Knawat/dropshipping-woocommerce#8]
Steps:

Go to your WooCommerce Store
Make sure you installed Knawat WooCommerce plugin
Navigate to Dropshipping > Knawat Setup
Click on **Connect With Knawat.com**
app.knawat.com dashboard window opened to confirm
confirm your store and set configuration

Actual result:
the popup still opened 

Expected result:
the popup should close automatically and redirects you back to the plugin with connected **message**

**Comment by iamdharmesh** [comment]
@HazemKhaled can you please redirect user to on requested redirect url in Popup after store configuration done successfully. issue will get auto fix.

**Comment by HazemKhaled** [comment]
OK, i'll today and deploy next release, will update here with next release

**Comment by iamdharmesh** [comment]
We have to refactor it as per New Product import approach. so moving it to Milestone v2.0.0

**Comment by iamdharmesh** [comment]
Deprecated because of new plugin approach.
