### ISSUE TITLE
Shopz.io, qTranslate-x and WooCommerce

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#89]
We are using qTranslate-x for multilingual WooCommerce, and recommend Shopz.io for e-commerce mobile applications.

Shopz.io GraphQL plugin working fine with qTranslate-x, except the variations, check image
![img_f952f9e6c2b9-1 2](https://user-images.githubusercontent.com/125433/51985765-bb31f180-24af-11e9-8d0b-07e2bf3a7be4.jpeg)

**Comment by iamdharmesh** [comment]
Fixed.
