### ISSUE TITLE
Knawat Order status

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#9]
Knawat has more detailed status and shipping info, we sending it now as order meta

Acceptance criteria:
1. admin can see Knawat order status with of WooCommerce order status in case it's Knawat order (ex: Shipped _Completed_)
2. User also can see in the website knawat order status beside the regular one

**Comment by iamdharmesh** [comment]
@abdullah-albakour please test and mark this closed.
