### ISSUE TITLE
problem in the  shop page 

### ISSUE THREAD

**Issue by mahmoudalakkad** [Knawat/dropshipping-woocommerce#92]
Dear Hazem .. 

I have a problem in the  shop page 
![duccany3](https://user-images.githubusercontent.com/49037644/55178065-5c29e980-518d-11e9-8650-ba63f9408793.PNG)

the page does not support arabic , Though translated

A message appears(Sorry, this entry exists only in US English.)url : http://duccany.com/cart/
I use translation  (qTranslate-x ) 

thank you

**Comment by esl4m** [comment]
Problem solved (plugin conflicts)
- Disable Knawat plugin .
- Remove all products 
- Activate the plugin again and import .
