### ISSUE TITLE
issues in variety product

### ISSUE THREAD

**Issue by mahmoudalakkad** [Knawat/dropshipping-woocommerce#93]
Dear Hazem .. 

I have a problem in the attributes in my site
The problem is that the attributes  appear  English  on the Arabic version

URL : http://duccany.com/product/opened-shoulders-printed-t-shirt/

I have a problem with Hide attributes  in some products
the problem is that hide attributes are deleted from the knawat catalog 

URL : http://duccany.com/product/boys-orange-polo-neck-t-shirt/

thank you
![duccany1](https://user-images.githubusercontent.com/49037644/55178332-dbb7b880-518d-11e9-8f1d-b1599a41240b.PNG)

![duccany](https://user-images.githubusercontent.com/49037644/55178378-ea05d480-518d-11e9-8d06-deb4526186e5.PNG)

**Comment by esl4m** [comment]
@mahmoudalakkad 
URL : http://duccany.com/product/boys-orange-polo-neck-t-shirt/
Product out of stock and there is a message on admin dashboard says that the product is our of stock.
..
Please make sure to check the product availabilty then check the attibutes (sizes). 
If issue still exists , you can reopen this issue.
