### ISSUE TITLE
Warning message for woocommerce Knawat plugin users

### ISSUE THREAD

**Issue by samer2023** [Knawat/dropshipping-woocommerce#96]
WARNING MESSAGE FOR WOOCOMMERCE KNAWAT PLUGIN USERS : 

Notice: wc_rest_system_status_controller was called incorrectly. Classes that extend the WooCommerce/WordPress REST API should only be loaded during the rest_api_init action, or should call WC()->api->rest_api_includes() manually. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Knawat_Dropshipping_Woocommerce->init_includes, require_once('/plugins/dropshipping-woocommerce/includes/api/class-dropshipping-woocommerce-handshake.php'), class_exists, spl_autoload_call, WC_Autoloader->autoload, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.6.) in /home/abbalac1/public_html/wp-includes/functions.php on line 4667

An internet search reveals that another plugin with the same error was updated to resolve the issue.

**Comment by nicktirdea** [comment]
It looks that this error triggers another one:
 PHP Warning:  Cannot modify header information - headers already sent by (output started at /home2/mysite/public_html/wp-includes/functions.php:4773) in /home2/mysite/public_html/wp-includes/rest-api/class-wp-rest-server.php on line 1258

**Comment by nicktirdea** [comment]
I can't save changes in Customize/Additional CSS section. Such message pops-up: “Looks like something’s gone wrong. Wait a couple seconds, and then try again.” Do you face similar issue?

**Comment by esl4m** [comment]
issue in file
dropshipping-woocommerce.php line # 182
replace this line:
`require_once KNAWAT_DROPWC_PLUGIN_DIR . 'includes/api/class-dropshipping-woocommerce-handshake.php'; `

with:
`add_action("init", function () {
				require_once( KNAWAT_DROPWC_PLUGIN_DIR . 'includes/api/class-dropshipping-woocommerce-handshake.php');
			}); `

Will add it in the next plugin update.

**Comment by nicktirdea** [comment]
I modified the code in file, but that issue remained. Will wait for plugin update.
[dropshipping-woocommerce (edited).zip](https://github.com/Knawat/dropshipping-woocommerce/files/3178463/dropshipping-woocommerce.edited.zip)
